language: python

python:
- "3.5"

cache: pip

addons:
  apt:
    packages:
    - libpq-dev

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - IDENTITY_SERVICE=null
  - MIGRATIONS_PATH=migrations
  - DATABASE_URL=null
  - CLIENTS=null

install:
- pip install -r requirements.txt
- python setup.py install

script:
- coverage run --source=inventory --module unittest discover --verbose

after_success:
- coveralls

deploy:
- provider: script
  skip_cleanup: true
  script: bin/togemfury.sh
- provider: heroku
  app: ocelot-saas-inventory
  run: bin/migrate.sh
  api_key:
    secure: "ql8yYWvkIQEgaIelpo03Z68OCIdyxzdU4HkD7G51Z5Z9pbnNV/pBd6N9PK5tGyvVLvAyc12oZ1FbSMkH8wjPLmiB9hHDNq7r6MjIdB5+9QbsZKPumYPHobrMcXzFrp1cSQLTxooq6CT2o/aT/6Q0zGz7MLGRa/qzHrVbCN1BkHlF41TI4JNozcuogtrwhKJ27OWr2/f3yyuYC9h2YPzEHR8un+89Z8cDaKLLlh8pQ6JBt8Vwlp4/zw8htdX4wSPDaQDY+56bPfku9Fpj2gjsjdA7KJ48flavqhaM9ongjMjM2XqKva9khU+dwVgLHLzk9k0n2zK35t6jCAGjr42JFyNqnQ+6QsiaU2tkkh3Hr9jNcr4XU32TAP2101dpszpeSJkZCn6b1PufxkXcJva0SIdNFpP9oRrZ9qSu1O1SBji++duoiP7D5RQdXKP//SDo79nNJP4hxXGicEolT8Y0cm7J4h5cPH1TZZFFlpSgJzk9s3OmMqna8AHV15VPJJ96ruqlhEj6K+9+BM+xgv5DgFSar9izLg8DsXoY3/ELizcfz8tmOcw4+H3uUVHlsH0vPCAa5oV9IWLhPGjQzj+HRwrSYDYHPuTbQpEHc6U091WEdDpzoT96mXI0av7OUgYgDn5Zz57dQtxHbAUGgnZuJ8gGdF6p2YsUk1LiuPzxfGY="
